Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [

    path('cart/<int:p>',views.add_cart,name="addcart"),
    path('cart_view',views.cart_view,name="cart_view"),
    path('cart_remove/<int:p>',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:p>',views.full_remove,name="full_remove"),
    path('order_form/',views.order,name="order_form"),
    path('orderview/',views.orderview,name="order_view"),
]

Ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [

    path('search/',views.search,name="sresult"),

]

Ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [

    path('',views.allprodCat,name="allprodcat"),
    path('view/<slug:cslug>',views.allproducts,name="views"),
    path('detail/<slug:bslug>',views.prodetail,name="detail"),
    path('signup/',views.register,name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

]

Ecommerce/cart/models.py
from django.db import models
from shop.models import product
from django.contrib.auth.models import User

class cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products = models.ForeignKey(product,on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    active = models.BooleanField(default=True)

    def subtotal(self):
        return self.quantity*self.products.price

    def __str__(self):
        return self.products.name
class Account(models.Model):
    acctnumber = models.CharField(max_length=200)
    accttype = models.CharField(max_length=200)
    amount =models.IntegerField()
    def __str__(self):
        return self.acctnumber
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    products = models.ForeignKey(product,on_delete=models.CASCADE)
    address = models.TextField()
    phone = models.CharField(max_length=200)
    order_status = models.CharField(max_length=30,default="pending")
    delivery_status = models.CharField(max_length=30,default="pending")
    noofitems = models.IntegerField()

    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    def subtotal1(self):
        return self.noofitems*self.products.price

Ecommerce/search/models.py
from django.db import models

# Create your models here.

Ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from cart.models import cart,Account,Order
from shop.models import product
#from django.http import HttpResponse

@login_required
def cart_view(request):
    total=0
    try:
        user = request.user
        cartitems = cart.objects.filter(user=user)
        for i in cartitems:
            total += i.quantity*i.products.price
    except cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cartitems,'total':total})

@login_required()
def add_cart(request,p):
    products = product.objects.get(id=p)
    user = request.user
    try:
        cart1 = cart.objects.get(products=products,user=user)
        if cart1.quantity < cart1.products.stock:
            cart1.quantity += 1
        cart1.save()
    except cart.DoesNotExist:
        cart1 = cart.objects.create(products=products,user=user,quantity=1)
        cart1.save()

    return redirect('cart:cart_view')

@login_required
def cart_remove(request,p):
    user = request.user
    products = product.objects.get(id=p)
    try:
        cart1 = cart.objects.get(user=user,products=products)
        if cart1.quantity > 1:
            cart1.quantity -= 1
            cart1.save()
        else:
            cart1.delete()
    except:
        pass
    return redirect('cart:cart_view')
@login_required
def full_remove(request,p):
    user = request.user
    products = product.objects.get(id=p)
    try:
        cart1 = cart.objects.get(user=user,products=products)
        cart1.delete()

    except:
        pass

    return redirect('cart:cart_view')

@login_required
def order(request):
    total = 0
    items = 0
    msg = 0
    if (request.method == "POST"):
        a = request.POST['a']
        b = request.POST['b']
        c = request.POST['c']
        user = request.user
        cart1 = cart.objects.filter(user=user)
        for i in cart1:
            total += i.quantity*i.products.price
            items+=i.quantity

        ac = Account.objects.get(acctnumber=c)
        if float(ac.amount) >= total:
                ac.amount = ac.amount-total
                ac.save()
                for i in cart1:
                    o = Order.objects.create(user=user,products=i.products,address=a,phone=b,order_status="paid",noofitems=i.quantity)
                    o.save()
                cart1.delete()
                msg ="ordered placed successfully"
                return render(request,'orderdetail.html',{'msg':msg,'total':total,'items':items})
        else:
                msg="insufficient amount.you cant place order."
                return render(request,'orderdetail.html',{'msg':msg})

    return render(request,'orderform.html')

def orderview(request):
    user = request.user
    o=Order.objects.filter(user=user,order_status="paid")
    return render(request,'orderview.html',{'o':o,'name':user.username})

Ecommerce/search/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q
def search(request):
    products=None
    query=None
    if request.method=="POST":
        query=request.POST.get('q')
        if query:
            products=product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'p':products})

Ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'css/customs.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

</head>
<body>
<div class="container-fluid">
    <header>
    <center>
        <img src="{% static 'img/logo.jpg' %}" height="100px" width="100px">
    </center>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:rgb(0, 153, 153)">
  <div class="container-fluid">

    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All categories</a></li>
            {% for i in links %}
              <li><a class="dropdown-item" href="{% url 'shop:views' i.slug %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
   <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:order_view' %}" >your orders</a>
        </li>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}" >logout</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_view' %}"><i class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
        </li>


          {% else %}

              <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:signup' %}" >register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:login' %}" >login</a>
        </li>

           {% endif %}
      </ul>

      <form class="d-flex"action="{% url 'search:sresult' %}" method="post">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>

    </div>
  </div>
</nav>
         </header>
        {% block content %}
        {% endblock %}

        <footer class="footer">
            <div>
                <p><i class="fa-regular fa-copyright"></i> Myshop pvt ltd. All rights reserved</p>
            </div>
        </footer>

</div>
</body>
</html>

Ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom=100px">
    {% if not cart %}
    <div>
        <h1 class="text-center">cart is empty</h1>
    </div>
    <div>
        <strong><a href="{% url 'shop:allprodcat' %}"> continue shopping</a></strong>
    </div>
    {% else %}
    <div class="row mx_auto">
        <h1 style="width:100%;">shopping cart</h1>

        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                <th colspan="6" class="text-center">
                    YOUR ITEMS
                </th></tr>
                    {% for i in cart %}
               <tr>
                   <td><img src="{{i.products.image.url}}" style="height:150px;width:150px"></td>
                   <td>{{i.products.name}}</td>
                   <td>p id:{{i.products.id}}<br>
                       unit price:{{i.products.price}}<br>
                       quantity:{{i.quantity}}*{{i.products.price}}<br>

                   </td>
                   <td>subtotal:{{i.subtotal}}</td>
                   {% if i.quantity < i.products.stock %}
                   <td><a href="{% url 'cart:addcart' i.products.id %}"><i class="fa-solid fa-circle-plus custom_icon"></i></a>
                       <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
                       <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-sharp fa-solid fa-trash custom_icon"></i></a>
                   </td>
                   {% else %}
                    <td>
                       <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
                       <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-sharp fa-solid fa-trash custom_icon"></i></a>
                   </td>
                   {% endif %}
               </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}
        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                    <th colspan="5" class="text-center">checkout</th>
                </tr>
                <tr>
                    <th colspan="5">Total price:   {{total}}</th>
                </tr>
            </table>
            <a href="{% url 'shop:allprodcat' %}" class="btn btn-primary">continue shopping</a>
            <a href="{% url 'cart:order_form' %}" class="btn btn-primary" >place order</a>
        </div>
    </div>
</div>
{% endblock %}

Ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img/banner.jpg' %}" height="300px" width="100%">
</div>
<div>
  <h1 class="text-center">OUR COLLECTIONS</h1>
<p>All our products are developed with a complete dedication to quality,durability, and functionality.Online shopping is a form of electronic commerce which allows consumers to directly buy goods or services from a seller over the Internet using a web browser or a mobile app.Online shopping is the process whereby consumers directly buy goods or services from a seller in real-time, without an intermediary service, over the Internet. It is a form of electronic commerce. An online shop, eshop, e-store, Internet shop, webshop, webstore, online store, or virtual store evokes the physical analogy of buying products or services at a bricks-and-mortar retailer or in a shopping center.</p>
</div>
  <div class="container" style="margin-bottom:100px;">
  <div class="row mx-auto">
    {% for i in c %}
<div class="card  border  border-dark me-5" style="width: 18rem;">
  <img src="{{i.image.url}}" style="height:200px;width:100%"class="card-img-top" alt="...">
  <div class="card-body" >
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'shop:views' i.slug %}" class="btn btn-primary">product</a>
  </div>
</div>
{% endfor %}
  </div>
  </div>
{% endblock %}

Ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mx-auto">
    <div class="col-sm-6">
        <img src="{{b.image.url}}" height="500px" width="100%" alt="{{b.image.url}} ">
    </div>
        <div class="col-sm-6">
            <div>
                <h1 class="a">{{b.name}}</h1>
                <p>{{b.price}}</p>
                <h3 class="new">product description</h3>
                <p>{{b.description}}</p>
                {% if b.stock <= 0 %}
                <h2> OUT OF STOCK</h2>
                {% else %}
                <a class="btn btn-primary" href="{% url 'cart:addcart' b.id %}">ADD TO CART</a>
                {% endif %}>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>login</h1>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label  class="form-label">Username</label>
      <input type="text"  class="form-control" name="a" placeholder="Enter username">
    </div>
     <div class="mb-3">
      <label  class="form-label">Password</label>
      <input type="password" class="form-control" name="e" placeholder="Enter password">
    </div>
    <div class ="mb-3">
          <input type="submit" class="form-control">
    </div>
    </form>
{% if messages %}
{% for i in messages %}
<ul class ="messages">
    <l1>{{i}}</l1>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

Ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class ="container" style="margin-bottom:100px;">
<h1 class ="text-success"> your order placed successfully{{total}}</h1>
<p> thankyou....!</p>
    <a class="btn btn-primary">{% url 'shop:allprodcat' %}</a>
</div>
</center>
    {% endblock %}

Ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>order form</h1>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label  class="form-label">Address</label>
        <textarea class="form-control" name="a" placeholder="Enter address" rows="3"></textarea>
    </div>
     <div class="mb-3">
      <label  class="form-label">Phone number</label>
      <input type="number" class="form-control" name="b" placeholder="Enter phone number">
    </div>
         <div class="mb-3">
      <label  class="form-label">Account number</label>
      <input type="number" class="form-control" name="c" placeholder="Enter acct number">
    </div>
    <div class ="mb-3">
          <input type="submit" class="form-control">
    </div>
    </form>

{% endblock %}

Ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <center><b><h1 class="text-danger">your ordered items</h1></b></center>
  <table class="table table bordered border-dark">
  <tr>
    <td>username:{{user}}</td>

  </tr>
  </table>
    <div class="row mx-auto">
        <table class="table table bordered border-dark">
        {% for i in o %}
           <tr>
   <td><img src="{{i.products.image.url}}" style="height:150px;width:150px"></td>
                   <td><b>product name:  {{i.products.name}}</b></td>
                   <td><b>delivery address:  {{i.address}}<br>
                       phone number:{{i.phone}}<br>
                       p id:{{i.products.id}}<br>
                       quantity:{{i.noofitems}}<br>
                       price:{{i.products.price}}<br>
                       subtotal:{{i.subtotal1}}<br>
                       ordered on :{{i.date_added}}</b></td><br>
      </tr>
     {% endfor %}
</table>
</div>
</div>
{% endblock %}

Ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>user register</h1>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label  class="form-label">Username</label>
      <input type="text"  class="form-control" name="a" placeholder="Enter username">
    </div>
    <div class="mb-3">
      <label class="form-label">First name</label>
      <input type="text" class="form-control" name="b" placeholder="Enter firstname">
    </div>
    <div class="mb-3">
      <label class="form-label">Last name</label>
      <input type="text" class="form-control" name="c" placeholder="Enter lastname">
    </div>
     <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="text" class="form-control" name="d" placeholder="Enter email">
    </div>
     <div class="mb-3">
      <label  class="form-label">Password</label>
      <input type="password" class="form-control" name="e" placeholder="Enter password">
    </div>
  <div class="mb-3">
      <label  class="form-label">Confirm Password</label>
      <input type="password" class="form-control" name="f" placeholder="Enter conformpw">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock %}

Ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
  <div>
    <h3>you have searched for {{query}}</h3>
  </div>
</center>

<div class="container" style="margin-bottom:100px;">
  <div class="row m-2">
    {% for i in p %}
<div class="card  border  border-dark me-5" style="width: 18rem;">
  <img src="{{i.image.url}}" style="height:200px;width:100%"class="card-img-top" alt="...">
  <div class="card-body" >
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'shop:detail' i.slug %}" class="btn btn-primary">DETAILS</a>
  </div>
</div>

    {% empty %}
    <div>
      <p> 0 results found</p>
    </div>
     {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{a.image.url}}" height="500px" width=100%">
</div>
<div>
  <h1 class="text-center">{{a.name}}</h1>
    <p class="text-justify"></p>
</div>
  <div class="container" style="margin-bottom:100px;">
  <div class="row m-2">
    {% for i in p %}
<div class="card  border  border-dark me-5" style="width: 18rem;">
  <img src="{{i.image.url}}" style="height:200px;width:100%"class="card-img-top" alt="...">
  <div class="card-body" >
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'shop:detail' i.slug %}" class="btn btn-primary">DETAILS</a>
  </div>
</div>
{% endfor %}
  </div>
  </div>

{% endblock %}